""" File to hold values that should not be configurable. """

TRACKER_HISTORY_COUNT = 100

SOFTMAX_T_SINGLE = 1.0

SOFTMAX_T_FINAL = 1.0

LANG_PASS_THRESHOLD = 2

MAX_MGPT_PROMPT_LENGTH = 256

MAX_WENZONG_PROMPT_LENGTH = 256

MIN_PROMPT_LENGTH = 32

MAX_PROMPT_LENGTH = 64